blank_issues_enabled: false
contact_links:
  - name: PawsomeVencord Support Server
    url: https://discord.gg/w9jVtzNx4c
    about: If you need help regarding Pawtop or PawsomeVencord, please join our support server!
