/*
 * Vesktop, a desktop app aiming to give you a snappier Discord Experience
 * Copyright (c) 2025 Vendicated and Vesktop contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import "./themedSplash";
import "./ipcCommands";
import "./appBadge";
import "./fixes";
import "./arrpc";
import "__patches__"; // auto generated by the build script

export * as Components from "./components";
import { onceReady } from "@equicord/types/webpack";
import { Alerts, VoiceActions } from "@equicord/types/webpack/common";

import SettingsUi from "./components/settings/Settings";
import { VesktopLogger } from "./logger";
import { Settings } from "./settings";
export { Settings };

import type SettingsPlugin from "@equicord/types/plugins/_core/settings";

VesktopLogger.log("Pawtop v" + VesktopNative.app.getVersion());

const customSettingsSections = (Vencord.Plugins.plugins.Settings as any as typeof SettingsPlugin).customSections;

customSettingsSections.push(() => ({
    section: "Pawtop",
    label: "Pawtop Settings",
    element: SettingsUi,
    className: "vc-vesktop-settings"
}));

VesktopNative.voice.onToggleSelfMute(() => VoiceActions.toggleSelfMute());
VesktopNative.voice.onToggleSelfDeaf(() => VoiceActions.toggleSelfDeaf());

// TODO: remove soon
const equicordDir = "equicordDir" as keyof typeof Settings.store;
if (Settings.store[equicordDir]) {
    onceReady.then(() =>
        setTimeout(
            () =>
                Alerts.show({
                    title: "Custom PawsomeVencord Location",
                    body: "Due to security hardening changes in Pawtop, your custom PawsomeVencord location had to be reset. Please configure it again in the settings.",
                    onConfirm: () => delete Settings.store[equicordDir]
                }),
            5000
        )
    );
}
